### ISSUE TITLE
indoor_bike_data: Calculation of cadence is incorrect

### ISSUE THREAD

**Issue by wklenk** [zacharyedwardbull/pycycling#32]
Please check the calculation of cadence in file _pycycling/ftms_parsers/indoor_bike_data.py_

To get the value for _instant_cadence_ and _average_cadence_, the value is divided by 2. I think it has to be divided by 10 instead.

See https://github.com/oesmith/gatt-xml/blob/master/org.bluetooth.characteristic.indoor_bike_data.xml

**Comment by zacharyedwardbull** [comment]
Hey, thanks for raising this issue. 

I'm not very familiar with this protocol, @tensorturtle would you mind taking a look?

Cheers

**Comment by tensorturtle** [comment]
@wklenk Thanks for raising this issue. From the gatt-xml link you shared, I see this relevant line:
https://github.com/oesmith/gatt-xml/blob/4fd2ede1d3da9365fdc6dec89290c346581a03f9/org.bluetooth.characteristic.indoor_bike_data.xml#L117-L119
In my understanding, a resolution of 0.5 means there are 2 measurements per 1 RPM, meaning we must divide the measurement by 2 to get the RPM.
Could you expand on your reasoning for multiplying by 10 instead of 2?

In my real-world tests with my smart trainer I believe I got the correct RPM but re-testing is possible.

**Comment by tensorturtle** [comment]
@zacharyedwardbull Close because real values are correct on Elite Suito trainer using FTMS
